### ISSUE TITLE
'Pings Failing' shows no data in Grafana

### ISSUE THREAD

**Issue by mahoromax** [kennethprose/Foptimum#2]
Upload, Download and Latency are working fine, but the Pings Failing chart just shows 'no data'.

I'm super fresh to Grafana and Prometheus, but I made sure to use the newest version of the dashboard json.

When I go to inspect and refresh the query, I get the following structure for the response:

```
results:Object
  A:Object
    status:200
    frames:Array[1]
      0:Object
        schema:Object
          refId:"A"
          meta:Object
            typeVersion:Array[0,0]
            executedQueryString:"Expr: ping_currently_failing{job=\"prometheus\", instance=\"192.168.0.2:9191\"}
            Step: 2m0s"
          fields:Array[0]
        data:Object
          values:Array[0]
    refId:"A"
```

What I'm seeing is that the response is an Object A which contains frames which contains an array with an object named '0' (which is the data that should be visualized). But this object contains no data. So my guess is that Grafana is trying to show this nested data instead of the "name" of the object.

Since I'm using an Unraid Community Template, it could that some update did not arrive here and the way how the data is served to prometheus has changed. 
But if not, I hope to get help on how to adjust this visualization...

**Comment by kennethprose** [comment]
Hi @mahoromax,

What do you have the ping interval set to in the unraid docker template?

Can you post what you are seeing on the Foptimum webpage? Specifically the info at the bottom which should look something like this:

```
# HELP ping_currently_failing A true/false value. True when pings are currently in a failing state
# TYPE ping_currently_failing gauge
ping_currently_failing 0.0
# HELP ping_success_total Number of successful pings
# TYPE ping_success_total counter
ping_success_total 0.0
# HELP ping_success_created Number of successful pings
# TYPE ping_success_created gauge
ping_success_created 1.7014521223718402e+09
# HELP ping_fails_total Number of failed pings
# TYPE ping_fails_total counter
ping_fails_total 0.0
# HELP ping_fails_created Number of failed pings
# TYPE ping_fails_created gauge
ping_fails_created 1.7014521223718536e+09
```

**Comment by mahoromax** [comment]
Ping interval is set to 15

```
# HELP ping_currently_failing A true/false value. True when pings are currently in a failing state
# TYPE ping_currently_failing gauge
ping_currently_failing 0.0
# HELP ping_success_total Number of successful pings
# TYPE ping_success_total counter
ping_success_total 1641.0
# HELP ping_success_created Number of successful pings
# TYPE ping_success_created gauge
ping_success_created 1.70144637811526e+09
# HELP ping_fails_total Number of failed pings
# TYPE ping_fails_total counter
ping_fails_total 0.0
# HELP ping_fails_created Number of failed pings
# TYPE ping_fails_created gauge
ping_fails_created 1.7014463781152766e+09
```

The format seems equal.  Ping_Sucess_Total is also an interesting value, it fits to when I restarted the docker last time (worked on the server hardware)

**Comment by kennethprose** [comment]
Sorry for the delayed reply.

The ping_success is a positive number indicating that the pings are running and being recorded. It is possible that you just did not encounter any failing pings yet. When Grafana sees a value of 0, it will just display 'no data.'

Can you try disconnecting your host from the internet while it is running and then check to see if some failed pings have accumulated on that page?

**Comment by mahoromax** [comment]
Sooo
`ping_fails_total 5572.0`
kind of makes me think I already had quite a few failed pings before disabling internet access - which allowed me to still access the grafana and let all components communicate.

The dashboard still shows "no data".

Oh dear, I just noticed I added a local IP to ping in addition to 1.1.1.1 and 8.8.8.8 :-/  I removed it. And it definitely shows in the current answer that *ping_currently_failing 1.0* 
But the dashboard still shows "no data"...

**Comment by kennethprose** [comment]
@mahoromax  This was completely my fault. I for some reason added a reference to the IP address that I have Foptimum running on in my network in the graph config for pings failing. That reference has been removed now.

You should be able to download the new grafana dashboard json file I just committed and it should fix your issue.

Thanks for notifying me of the issue!

**Comment by mahoromax** [comment]
Can confirm, got a really nice graph now :)
Just weird that nobody noticed before. And I even have that IP in the entry post and didn't notice it wasn't fitting my network/entries 🙈

**Comment by kennethprose** [comment]
I distinctly remember looking at that IP in your original post and for some reason thought nothing of it lol. Oh well. Glad you are up and running!
